services:
  frontend:
    build: ./frontend
    networks:
      - mynetwork
    ports:
      - 5173:5173

  backend:
    build: ./backend
    networks:
      - mynetwork
    ports:
      - 8000:8000

networks:
  mynetwork:
    external: true
